[package]
name = "atmega168-hal"
version = "0.1.0"
authors = ["Karl Thorén <karl.h.thoren@gmail.com>"]
edition = "2018"

[features]
rt = ["avr-device/rt"]

[dependencies]
avr-hal-generic = { path = "../../avr-hal-generic/" }

[dependencies.avr-device]
version = "0.2.2"
features = ["atmega168"]
