[package]
name = "nano-every-examples"
version = "0.0.0"
authors = ["Bill Wiseman <bw@bibble.co.nz>"]
edition = "2018"
publish = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.1.0"
nb = "0.1.2"
embedded-hal = "0.2.3"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["nano-every"]
