[package]
name = "avrmodern-hal"
version = "0.0.1"

authors = ["Rahix <rahix@rahix.de>", "tvijlbrief@gmail.com"]
edition = "2021"
description = "HAL crate for modern attiny and AVR* microcontrollers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rahix/avr-hal"
keywords = ["avr", "arduino"]
categories = ["no-std", "embedded", "hardware-support"]

[features]
rt = ["avr-device/rt"]
device-selected = []
enable-extra-adc = []
attiny402 = ["avr-device/attiny402", "device-selected"]
attiny1614 = ["avr-device/attiny1614", "device-selected"]
#attiny3224 = ["avr-device/attiny3224", "device-selected"]
#avr128db28 = ["avr-device/avr128db28", "device-selected"]

#critical-section-impl = ["avr-device/critical-section-impl"]

# Allow certain downstream crates to overwrite the device selection error by themselves.
disable-device-selection-error = []

# We must select a microcontroller to build on docs.rs
docsrs = ["attiny402"]

[dependencies]
avr-hal-generic = { path = "../../avr-hal-generic/" }

[dependencies.avr-device]
#avr-device = { git = "https://github.com/rahix/avr-device", rev = "330cdf1fb1a7301b9d6cf62491c16e69d6aa7312" }
version = "0.7"

# Because this crate has its own check that at least one device is selected, we
# can safely "circumvent" the check in `avr-device`.
#
# Why would we want that?  Otherwise, as `avr-device` is compiled first, its
# error will be shown and ours won't which leads to a degraded user experience
# as the displayed error message does not really tell what needs to be done...
features = ["device-selected"]

[package.metadata.docs.rs]
features = ["docsrs"]
