[general]
board = "promicro"

# The Pro Micro does not have a UART console like other Arduino boards.
# Instead, it can emulate a console device over USB, but this is not yet
# supported in `avr-hal`.  To get console output from a Pro Micro, you need to
# connect an external usb-serial converter to the TX/RX pins of your board.
open-console = false

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format
