name: Continuous Integration (ravedude)

on:
  push:
    branches:
      - main
      - next
      - wip
  pull_request:
    paths:
      - 'ravedude/**'

jobs:
  ravedude:
    name: "ravedude"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install libudev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Check ravedude
        run: |
          cargo check --manifest-path ravedude/Cargo.toml
      - name: Test ravedude
        run: |
          cargo test --manifest-path ravedude/Cargo.toml

  rustfmt:
    name: Apply rustfmt formatting (ravedude)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ravedude/Cargo.toml
